# -*- coding: utf-8 -*-
"""input_groundtruth_fusionRoad.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DJAt3tfGmMI8Boz3Q5J919_ksoPym01-
"""

# from google.colab import drive
# drive.mount('/content/drive')

# cd drive/MyDrive/dataset/RoadDataset

# rm -rf logs training_checkpoints

# ls

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the two images you want to concatenate
image1 = cv2.imread('999764_mask.png')  # Replace 'image1.jpg' with the path to your first image
image2 = cv2.imread('999764_sat.jpg')  # Replace 'image2.jpg' with the path to your second image

# Resize both images to 256x256 pixels
image1 = cv2.resize(image1, (256, 256))
image2 = cv2.resize(image2, (256, 256))

# Concatenate the two images horizontally
concatenated_image = np.concatenate((image1, image2), axis=1)

# Display the concatenated image using Matplotlib
cv2.imwrite('999764.jpg', concatenated_image)

# rm 999531_mask.png 999531_sat.jpg 999667_mask.png 999667_sat.jpg 999764_mask.png 999764_sat.jpg